-- Generated by scripts/hypr2lua.
-- Source: /home/hancore/.config/omarchy/themes/oxocarbon/hyprland.conf

hl.config({
  general = {
    col = {
      active_border = "rgb(8A8A8D)",
      inactive_border = "rgb(363636)",
    },
    border_size = 6,
    gaps_in = 5,
    gaps_out = 5,
  },
  decoration = {
    rounding = 4,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 8,
      range = 16,
      color = "rgba(22,22,22, 1)",
    },
  },
})
